spring:
  application:
    name: FlexiSchedule

  datasource:
    url: jdbc:postgresql://localhost:5432/flexi
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
